### PR TITLE
Fix issues with default.sreg handling

### PR DESCRIPTION
**Pull request by jhalmen**
simplify remote code, and make all configs optional. if they don't exist the defaults will be used.

* Heartbeat timeout config is now called HeartbeatTime (but the code will warn you if you configured something incorrectly)
  example:
```log
08/09/2020 16:13:01 - MainGui - WARNING - Experiment config key 'Heartbeat' does not exist.
                Possible keys: ['TimerTime', 'HeartbeatTime', 'InterpolationPoints', 'MovingWindowEnable', 'MovingWindowSize']
```

* also fixes startValue issue for slider.

i tried to test this as much as possible, hope i didn't include any regressions.

this seems to work well for me.

### CODE REVIEW

**Comment by jhalmen** [comment]
This may also be a good time to reconsider the naming of these config options:
- maybe rename the `Time` options to `Timeout`, as that's what they actually are
- `TimerTime` -- says nothing about what it actually does. maybe `Draw` or `Plot`?

**Comment by TanDro** [comment]
Works for me in tests, too

**Comment by jhalmen** [comment]
@TanDro so no rename of the `TimerTime`?

**Comment by TanDro** [comment]
@jhalmen in past we discuss this different time. Currently is used only to update the plot, right? Therfore, we can rename it to plotRefreshTime?

**Pull request merged**
